### ISSUE TITLE
Use Projects tab suggestion

### ISSUE THREAD

**Issue by CarlosRafael22** [city41/smaghetti#1]
Hello Matt! How are you doing?

I found out about you after reading a post on your blog "Javascript is a pass by value language". So I ended up checking your profile here and I am impressed by your work with this project! Congratulations on the amazing work!

I am just messaging to make a suggestion in case you haven't used it already, the Projects tab. I've only recently found out so I'm starting to use and thought it was a nice way to create task issues, link PRs and manage everything here on github just like we do on Trello. In case you haven't opted for that forget about my message, just thought about helping :)

Keep up the good work! Cheers :)

**Comment by city41** [comment]
hey Carlos, 

Thanks for the kind words! I'm surprised you found this repo :)

I have used the projects tab in the past, and I do like how it integrates with PRs and issues. But I also like how Trello allows screenshots and other features. I think for now I will stick with Trello, but if more people end up getting involved with this project, then switching to GitHub projects probably makes sense.

**Comment by CarlosRafael22** [comment]
Hi Matt!

You are welcome. I was surprised we could do such things with React haha Great work!

Yeaah, you are right! We cant do this with Projects and also cant comment on cards so makes more sense to use Trello indeed. Lets see if they change that later on. You can close this :)

I hope more people get involved here to help you build this awesome project! Wish you all the best :)

**Comment by city41** [comment]
Hey @CarlosRafael22 just a quick heads up I now have a github project going as interest in the editor has picked up a bit. Thanks again for the suggestion.

https://github.com/city41/smaghetti/projects/2

**Comment by CarlosRafael22** [comment]
Awesome news, Matt! Great to hear the interest is increasing! The editor is looking nice, keep up the great work! :)
