### ISSUE TITLE
Can't edit entities easily anymore

### ISSUE THREAD

**Issue by nintyalex** [city41/smaghetti#105]
I can't edit things like Brick and ? Blocks anymore since the copy function became available.

**Comment by city41** [comment]
ah crap. sorry about that, I didn't test this thoroughly enough. Working on a fix now.

**Comment by city41** [comment]
thanks for catching that @nintyalex, I need to be more careful before pushing changes.

The fix is now being deployed, it will be available in about 3-4 minutes from now.
