### ISSUE TITLE
SMA4 wowroms.com ROM Not Working 

### ISSUE THREAD

**Issue by antek320** [city41/smaghetti#153]
Hi, Im Using A SMA4 ROM From wowroms.com, And If I Try To Load The Rom, It Says "Checksum Failed, Wrong ROM?", I tried the .zip file and the .gba file, it didnt work, please fix this problem

**Comment by city41** [comment]
For legal reasons I can't talk about the rom much.

For dumps that are out on the internet, there are the 1.0 and 1.1 versions. Smaghetti is only compatible with the 1.1 version.
