### ISSUE TITLE
bullet bill resources are messed up

### ISSUE THREAD

**Issue by city41** [city41/smaghetti#167]
SMA4 has two different kinds of bullet bills, seems one is from SMB3 and the other from SMW. Smaghetti is not using the correct ones for most bullet bills. Also the palette should be `[0x7f96, 0x7fff, 0x18c6, 0x3192, 0x1636, 0x2a9c, 0x1f4, 0x29a, 0x37f, 0x42ff, 0x4a52, 0x6318, 0x77bd, 0x7ffb, 0x7fd2, 0x732c]` according to @lelegofrog

**Comment by lelegofrog** [comment]
fixed
[5772800](https://github.com/city41/smaghetti/commit/577280075428ef9d842f9e2a6117bc3bdc3dce3a)

**Comment by city41** [comment]
woohoo! thanks!
