### ISSUE TITLE
Room height limit is more than 63?

### ISSUE THREAD

**Issue by mariomadproductions** [city41/smaghetti#172]
You can get levels like [this](https://user-images.githubusercontent.com/9919020/175077098-fc668155-d49c-46cd-bae3-4f4d9b8ca71c.png) one that are more than 63 tiles tall, but I'm not sure what I am looking for in the hex tree to try this out for myself.

**Comment by city41** [comment]
![image](https://user-images.githubusercontent.com/141159/175108932-32adfed8-d142-48e5-b01d-f896e6d699a0.png)

So height is determined by "screen y boundary" under Level Settings. For this particular level it is set to `0xef`. I *think* what this value is, is the height of the room in pixels. My memory is vague because I did room height ages ago, but I remember there were some unknowns and taller rooms did strange things? I think? The 63 limit in Smaghetti is probably too restricting though.

**Comment by city41** [comment]
But `ef` for this room doesn't make any sense. If it reall is pixels, that only works to about 15 tiles.

This is what smaghetti does

```
	if (room.roomTileHeight !== INITIAL_ROOM_TILE_HEIGHT) {
		const heightInPixels = room.roomTileHeight * TILE_SIZE + 15;
		mostSigHeightInPixels = heightInPixels >> 8;
		leastSigHeightInPixels = heightInPixels & 0xff;
	}

	return [
		leastSigHeightInPixels, // screen y boundary, least sig byte
		mostSigHeightInPixels, // screen y boundary, most sig byt
```

Which supports this value is in pixels. But Mush6 doesn't support it. So unfortunately, room height remains a mystery.

**Comment by city41** [comment]
Also in Smaghetti's code is this

```
// 64 and up causes the map to wrap, and corrupts the level
export const MAX_ROOM_TILE_HEIGHT = 63
```

I think I will allow taller rooms, but if they go above 63 just warn you're in experimental territory. One sec, I'll see if I can get that in...

**Comment by city41** [comment]
https://user-images.githubusercontent.com/141159/175113487-e1597f67-211a-4754-bb9f-7f8a230a124e.mp4


Ah yeah, this is why. It's due to the GBA's background plane running out of room. Somehow the level tells the game it is taller but I don't know how yet.

**Comment by mariomadproductions** [comment]
I see, thanks for the update.

**Comment by mariomadproductions** [comment]
Does it work when you have a room with the proportions of the tall room in my example? Maybe its just very tall+wide rooms that don't work, or certain proportions that don't work.

**Comment by city41** [comment]
No, tall narrow rooms have the same problem. However, tall wrap around rooms fix the problem. You example, mushroom 6, is a wrap around room. And I can't think of any tall Nintendo made levels that aren't wrap around.

So when wrap around is turned on, the engine knows how to deal with this. Sadly, wrap around has plenty of its own problems and unknowns.

But, I will look into if you turn wrap around on in Smaghetti, then allowing rooms to be taller. That might be doable.

**Comment by city41** [comment]
Ok, if you make your room wrap-around, its heigh limit becomes 100 tiles.

But making your room wrap-around will likely move things around in unexpected ways. It gets worse the taller the room is. If you are diligent it is possible to keep playing the level and moving things until it is what you want, but that can be a lot of work. Some day we'll understand this movement and Smaghetti will handle it correctly.

**Comment by mariomadproductions** [comment]
> You example, mushroom 6, is a wrap around room.

Ah, I didn't realise that.

> And I can't think of any tall Nintendo made levels that aren't wrap around.

Just checked vgmaps for the main game and e-reader levels and that seems to be the case. Shame, I guess people will have to use warps at the top/bottom of a 63-tall normal rooms to work-around this.

Thanks
