### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by WinHack9702GitHub** [city41/smaghetti#185]
Level link:https://smaghetti.com/editor/MgXS97Uj/Shergiok-gay/
Original Level link:https://smaghetti.com/editor/yTZsRwfu/Handle-/
Reason: level stealed, remove pls

**Comment by city41** [comment]
Thanks for reporting this. I'll remove the level. If for no other reason, the name is against the TOS

**Comment by city41** [comment]
ok it has been removed
