### ISSUE TITLE
No objects placed after a Chargin' Chuck appear

### ISSUE THREAD

**Issue by bumptytobumpty** [city41/smaghetti#45]
That's because the Chargin' Chuck sprite is supposed to be 5-byte, if the fifth byte is set to 1 it will be a Clappin' Chuck

**Comment by city41** [comment]
Fixed with 3a824fe74b35bd89df59c7ef559907c70631b820

Thanks, nice catch. I'm going to file a new issue for adding support for clappin chuck. According to Mario Wiki those are the only two variants in SMA4.
