### ISSUE TITLE
FloatingBlock is likely a beach ball instead

### ISSUE THREAD

**Issue by bumptytobumpty** [city41/smaghetti#49]
If the byte that controls the rotating object gfx (like rotating blocks, seesaws, etc.) is set to 2, sprite e3 (FloatingBlock) will resemble a yellow-brown beach ball (which I'm pretty sure isn't used by anything else, it looks like ArrowLift without the arrow on it but it uses a different graphic) rather than the rotating blocks from Vexing Doors. Its collision also support this, and if you play a level with it in an emulator it makes ocean sound effects when it's moved around.

**Comment by city41** [comment]
oh nice! great find!

You also solved the mystery of [this byte](https://github.com/city41/smaghetti/blob/c41cb2f5dcb8559d5fd225bc7918e8c5186f5e14/src/levelData/createLevelData.ts#L191) in level settings. It must be `0` for arrow lift to work, but if you set it to `2`, then floating block becomes beach ball just as you said.

![image](https://user-images.githubusercontent.com/141159/120417683-4005d200-c32d-11eb-82ba-9e04e2550f6b.png)

looks like entities will for sure need another compatibility check with this byte.

I'm going to make a youtube video of the beach ball, want me to credit you for finding it?

**Comment by city41** [comment]
this is also good motivation to get sound working in smaghetti again. The emulator smaghetti uses does support sound, but I broke it when I added save state support.

**Comment by city41** [comment]
I did thank you in the video description: https://www.youtube.com/watch?v=anLR9PgHVC4

let me know if you want me to remove your name.

**Comment by city41** [comment]
related: https://github.com/city41/smaghetti/issues/24

**Comment by bumptytobumpty** [comment]
Another thing about the rotating (dynamic?) graphics set, they're all in 18af80, set width to 32 in a graphics viewer:
"Set 0" contains the tiles for the rotating block (0xDD), and a smaller one (which I think is unused, as the smaller rotating blocks (0xDE) actually use a resized version of the big block), the gray donut spike in its falling state, the falling spike (0xD3, 5-byte item), the pinball flipper, and arrow lift.

"Set 1" contains the tiles for the seesaw platform and the wire for the SMB1 balance platform (0xDF, 5-byte item, I had trouble getting this to appear though that could just be me).

"Set 2" contains the beach ball and tiles for minigame-related objects (like the ball you kick or moving death spikes)

**Comment by city41** [comment]
curious how you determined which set they are in? Looks like we have a good path forward to get all of these entities into smaghetti. SeeSaw platform has already been extracted, but it doesn't work since currently smaghetti always sets the rotation gfx set to `0`

btw if helpful, I have a tile viewer here: https://smaghetti.com/tools/tiles

but currently you gotta push "next" repeatedly to get to 18af80

![image](https://user-images.githubusercontent.com/141159/120423218-fff81c80-c337-11eb-82cb-5130e9a36c2b.png)

I'll update it to take an offset parameter

**Comment by bumptytobumpty** [comment]
I was using a program called "NLZ-GBA Advance"
https://www.romhacking.net/utilities/529/

**Comment by city41** [comment]
> I was using a program called "NLZ-GBA Advance"
> https://www.romhacking.net/utilities/529/

but that's just a tile viewer, right? how did you figure out which sets the beach ball, seesaw, etc are in?

**Comment by city41** [comment]
Closing this in favor of #52
