### ISSUE TITLE
objects that need sprite graphic sets determined

### ISSUE THREAD

**Issue by city41** [city41/smaghetti#60]
If an object is interactive, it becomes a sprite during interaction, and thus needs to declare which graphic sets it is compatible with. These objects need their sprite graphic sets determined:

* ~~fall away spike~~
* ~~music block~~
* ~~three way music block~~
* question block when it has a p-wing payload
* ~~donut block~~
* ~~Giant question block~~
* more?

brick with p-wing payload is interesting. always limit brick to p-wing graphic sets? possibly too limiting? have compatibility extend to object payloads (aye...)

**Comment by OQUENDOMAN** [comment]
HEY MATT I FOUND A COMPLETE DISASSEMBLY OF SMA4

https://www.dropbox.com/s/836ghm2jvg22ux8/sma4stuffs.7z

**Comment by city41** [comment]
MusicBlock and 3 way MusicBlock were fixed with 589ece571b3025ed26ab7863f43031bd407b6e8b

**Comment by city41** [comment]
I could have swore I saw fall away spike with garbled graphics, but in the latest dump it seems to work in all graphic sets. hmmm...

**Comment by city41** [comment]
donut block fixed in fc47bf93ea240b0f0c68481fcb642368d37e99cc

**Comment by city41** [comment]
giant question block was fixed with 1ce5d5ce5c578b1faa9ed67258b3ae1d5e96b813

very unexpectedly, it means qiant question block is incompatible with giant enemies, which does not seem correct. [Discussion started here](https://github.com/city41/smaghetti/discussions/125)

**Comment by city41** [comment]
these are all fixed
