### ISSUE TITLE
Reverse engineerings yet to be integrated

### ISSUE THREAD

**Issue by city41** [city41/smaghetti#87]
This issue is capturing all current reverse engineering findings that have yet to be added to the editor

* ~~[edge of screen teleports](https://github.com/city41/smaghetti/discussions/79)~~
* [level settings unknown 2 controls extra background y](https://github.com/city41/smaghetti/discussions/86)
* ~~[parachute generation stopper](https://github.com/city41/smaghetti/discussions/86)~~
* ~~[SMW style bullet bill generators](https://github.com/city41/smaghetti/discussions/86)~~
* ~~[bowser fire generator](https://github.com/city41/smaghetti/discussions/86)~~
* [prevent backwards scroll sprite](https://github.com/city41/smaghetti/discussions/86)
* ~~[bowser's fireball sprite](https://github.com/city41/smaghetti/discussions/86)~~
* [underwater levels](https://github.com/city41/smaghetti/discussions/69)
* ~~[prevent forward scrolling sprite](https://github.com/city41/smaghetti/discussions/62)~~

as I work on these, I'll update this issue and add comments. For more complex things, will probably branch out into a new issue.

**Comment by city41** [comment]
@bumptytobumpty @nintyalex @mariomadproductions just a heads up. this issue is a good place to see when findings get integrated. let me know if I missed any.

feel free to keep adding new discussions, I will update this issue accordingly.

**Comment by nintyalex** [comment]
Most of those lead to the Teleports discussion, though...

**Comment by city41** [comment]
oh damn, thanks, copy/paste error

**Comment by city41** [comment]
ScrollStopHorizontal was added with e9f4d042911a8c414ddc580ce69705eede63ed31

**Comment by city41** [comment]
edge of screen warps are added with b486d9fc75f1297dad0239aa8b498546a16134fd

ping @mariomadproductions

it looks like they are two tiles tall, pretty much just like doors. And they do work from both directions.

the fifth byte is set to zero for now, I've not explored what that byte does. Possibly it enables the warp to be taller?

**Comment by OQUENDOMAN** [comment]
HEY MATT I FOUND A COMPLETE DISASSEMBLY OF SMA4

https://www.dropbox.com/s/836ghm2jvg22ux8/sma4stuffs.7z

**Comment by city41** [comment]
bowser fireball generator has been added in 99b5d59d3044060c5f0c3170274afe602c7aaa47 ping @bumptytobumpty

**Comment by city41** [comment]
bowser fireball has been added in 04907c6b8d00793e979023e88eaa3fcb54158d67

**Comment by city41** [comment]
bullet bill generators were added in c917bfa0953b08e96b12a9280dfe1157eb9b126b and the canceler was added in 786e05bf434b7ddaf4ab0fb8504c98bf0f36a578

**Comment by city41** [comment]
parachute generator canceler was added in be3e86e0852d159b70cb7f6c5fdb385b7cc2c410

**Comment by city41** [comment]
these are all integrated
